### ISSUE TITLE
Open VSX Registry please?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscobol-themes#1]
The themes look nice, can you please co-publish them in the Open VSX Registry (which is, for example now also the default "market place" for VSCodium)?
Ideally also removing the outdated COBOL plus pack on the way (it was removed from the ms marketplace but is still listed in the registry).

Thank you!

**Comment by spgennard** [comment]
I cannot remove it, as "npx" does not have a removal mechanism, the best I can do is request it to be removed by raising an issue, which I have done.

Added.

**Comment by GitMensch** [comment]
Thanks for publishing the new one and for https://github.com/eclipse/open-vsx.org/issues/24.
